--liquibase formatted sql
--changeset RAML:e1b11888-aafb-4a5f-a489-2305d2e596e3  runOnChange:true


CREATE OR REPLACE VIEW datamerge.V_APPOINTMENT_OVERVIEW AS
SELECT 
    CAST(a.SCHEDULE_ID AS VARCHAR(200)) AS SCHEDULE_ID,
    CAST(
        CASE 
            WHEN c.ACCESS_GRANTED THEN a.MEMBER_ID  
            ELSE p.ANONYMIZED_MEMBER_ID             
        END AS VARCHAR(200)
    ) AS MEMBER_ID,
    a.APPOINTMENT_SESSION_ID,
    a.GROUP_ID,
    a.SEQUENCE_NUM,
    a.IS_LATEST_SESSION,
    CAST(a.ROLE_TITLE AS VARCHAR(400)) AS ROLE_TITLE,
    CASE 
        WHEN c.ACCESS_GRANTED THEN a.START_DATETIME  
        ELSE DATEADD(HOUR, o.TIME_ADJUSTMENT, a.START_DATETIME)   
    END AS START_DATETIME,
    CASE 
        WHEN c.ACCESS_GRANTED THEN a.END_DATETIME  
        ELSE DATEADD(HOUR, o.TIME_ADJUSTMENT, a.END_DATETIME)   
    END AS END_DATETIME,
    a.DURATION_MINUTES,
    CAST(a.STATUS_TITLE AS VARCHAR(400)) AS STATUS_TITLE,
    CAST(a.DETAILED_STATUS AS VARCHAR(400)) AS DETAILED_STATUS,
    CAST(a.CATEGORY AS VARCHAR(400)) AS CATEGORY,
    CAST(a.LOCATION_NAME AS VARCHAR(400)) AS LOCATION_NAME,
    CAST(a.FACILITY_INFO AS VARCHAR(400)) AS FACILITY_INFO,
    CAST(a.ROOM_DETAILS AS VARCHAR(400)) AS ROOM_DETAILS,
    CAST(a.REASON_DESCRIPTION AS VARCHAR(400)) AS REASON_DESCRIPTION,
    CAST(a.STAFF_NAME AS VARCHAR(400)) AS STAFF_NAME,
    CASE 
        WHEN c.ACCESS_GRANTED THEN a.LAST_MODIFIED_DATETIME  
        ELSE DATEADD(HOUR, o.TIME_ADJUSTMENT, a.LAST_MODIFIED_DATETIME)   
    END AS LAST_MODIFIED_DATETIME,
    a.ACTIVE_FLAG,
    CAST(a.DATA_SOURCE_CODE AS VARCHAR(200)) AS DATA_SOURCE_CODE
FROM 
    HEALTHDB.MEMBER_APPOINTMENTS a
JOIN 
    HEALTHDB.MEMBER_INFO p ON a.MEMBER_ID = p.MEMBER_ID
LEFT JOIN 
    CONFIGURATION.TIME_ADJUSTMENTS o ON o.MEMBER_ID = a.MEMBER_ID
LEFT JOIN 
    CONFIGURATION.ACCESS_CONTROL_RULES c ON c.ROLE_NAME = CURRENT_ROLE()
WHERE 
    a.ACTIVE_FLAG = 'TRUE'
    AND p.MEMBER_ID <> '-1';
